version: 0.1.{build}
branches:
  except:
  - /.*-wip/
skip_tags: true
image: Visual Studio 2019
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.props'
  version: '{version}'
environment:
  GitAccessToken:
    secure: dKFXXbtrNHur90Fk0K0s0Z08TDSwAQ8eA0x/1GNp5bdIQly9N3J4o2s6K3io09ob
  RedisTestEndpoint:
    secure: QnE1NdfRE6ymk/w9idrTsLNWU5lyqWk6PKF3tZEwIYoTf+jHx6khnTy/2Bhayha6VzwEsbHV6heQKl2/SqE6MQ==
  RedisTestPassword:
    secure: wj5VI/BQkunSJ8RY5/LYrJFg2PfaOeCOLVR5VBi8T/na8iOYimNovMZYO3iL5GG1
before_build:
- cmd: nuget restore ./src/CacheMeIfYouCan.sln
build:
  publish_nuget: true
test:
  assemblies:
    except:
    - Benchmarks*
deploy:
- provider: NuGet
  api_key:
    secure: uasmn1KlP1l2JFJjq3aypRW7OCmIbohgOU8k+vUwdJnGcSDNxty7ElcI1tumvzqx
  on:
    branch: release
after_deploy:
- ps: >-
    git config --global credential.helper store

    Add-Content "$HOME\.git-credentials" "https://$($env:GitAccessToken):x-oauth-basic@github.com`n"

    git config --global user.email "hamishpeebles@gmail.com"

    git config --global user.name "Hamish Peebles"

    git tag v$env:APPVEYOR_BUILD_VERSION

    git push --tag -q