name: $(majorVersion).$(minorVersion).$(Rev:r)

trigger:
- master

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: Release
  pathToSolutionFile: CacheMeIfYouCan.sln
  pathToMainTestProject: tests/CacheMeIfYouCan.Tests/CacheMeIfYouCan.Tests.csproj
  pathToCronTestProject: tests/CacheMeIfYouCan.Cron.Tests/CacheMeIfYouCan.Cron.Tests.csproj
  pathToPollyTestProject: tests/CacheMeIfYouCan.Polly.Tests/CacheMeIfYouCan.Polly.Tests.csproj
  pathToRedisTestProject: tests/CacheMeIfYouCan.Redis.Tests/CacheMeIfYouCan.Redis.Tests.csproj
  
steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: $(pathToSolutionFile)
    configuration: $(buildConfiguration)

- task: DotNetCoreCLI@2
  displayName: Test CacheMeIfYouCan
  inputs:
    command: test
    projects: $(pathToMainTestProject)
    framework: netcoreapp3.1
    configuration: $(buildConfiguration)
    nobuild: true

- task: DotNetCoreCLI@2
  displayName: Test CacheMeIfYouCan.Cron
  inputs:
    command: test
    projects: $(pathToCronTestProject)
    framework: netcoreapp3.1
    configuration: $(buildConfiguration)
    nobuild: true

- task: DotNetCoreCLI@2
  displayName: Test CacheMeIfYouCan.Polly
  inputs:
    command: test
    project: $(pathToPollyTestProject)
    framework: netcoreapp3.1
    configuration: $(buildConfiguration)
    nobuild: true

- task: DotNetCoreCLI@2
  displayName: Test CacheMeIfYouCan.Redis
  inputs:
    command: test
    framework: netcoreapp3.1
    configuration: $(buildConfiguration)
    nobuild: true

- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: pack
    packagesToPack: 'src/**/*.csproj'
    versioningScheme: byBuildNumber
    framework: netcoreapp3.1
    configuration: $(buildConfiguration)
    nobuild: true

- task: NuGetCommand@2
  displayName: Publish
  inputs:
    command: push
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    feedsToUse: select
    nuGetFeedType: internal
    publishVstsFeed: Default