name: $(majorVersion).$(minorVersion).$(Rev:r)

trigger:
- master

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: Release
  pathToSolutionFile: CacheMeIfYouCan.sln
  pathToMainTestProject: tests/CacheMeIfYouCan.Tests/CacheMeIfYouCan.Tests.csproj
  pathToCronTestProject: tests/CacheMeIfYouCan.Cron.Tests/CacheMeIfYouCan.Cron.Tests.csproj
  pathToPollyTestProject: tests/CacheMeIfYouCan.Polly.Tests/CacheMeIfYouCan.Polly.Tests.csproj
  pathToRedisTestProject: tests/CacheMeIfYouCan.Redis.Tests/CacheMeIfYouCan.Redis.Tests.csproj
  pathToSerializersTestProject: tests/CacheMeIfYouCan.Serializers.Tests/CacheMeIfYouCan.Serializers.Tests.csproj
  
steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: $(pathToSolutionFile)
    arguments: --configuration $(buildConfiguration)

- task: DotNetCoreCLI@2
  displayName: Test CacheMeIfYouCan
  inputs:
    command: test
    projects: $(pathToMainTestProject)
    arguments: --configuration $(buildConfiguration) --framework netcoreapp3.1 --no-build

- task: DotNetCoreCLI@2
  displayName: Test CacheMeIfYouCan.Cron
  inputs:
    command: test
    projects: $(pathToCronTestProject)
    arguments: --configuration $(buildConfiguration) --framework netcoreapp3.1 --no-build

- task: DotNetCoreCLI@2
  displayName: Test CacheMeIfYouCan.Polly
  inputs:
    command: test
    projects: $(pathToPollyTestProject)
    arguments: --configuration $(buildConfiguration) --framework netcoreapp3.1 --no-build

- task: DotNetCoreCLI@2
  displayName: Test CacheMeIfYouCan.Redis
  inputs:
    command: test
    projects: $(pathToRedisTestProject)
    arguments: --configuration $(buildConfiguration) --framework netcoreapp3.1 --no-build

- task: DotNetCoreCLI@2
  displayName: Test Serializers
  inputs:
    command: test
    projects: $(pathToSerializersTestProject)
    arguments: --configuration $(buildConfiguration) --framework netcoreapp3.1 --no-build

- task: DotNetCoreCLI@2
  displayName: Create Packages
  inputs:
    command: pack
    packagesToPack: 'src/**/*.csproj'
    versioningScheme: byBuildNumber
    arguments: --configuration $(buildConfiguration) --no-build

- task: NuGetCommand@2
  displayName: Publish Packages
  inputs:
    command: push
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    feedsToUse: select
    nuGetFeedType: internal
    publishVstsFeed: Default